### ISSUE TITLE
 Timeout: No businesses found. when theres excectly one result on search page

### ISSUE THREAD

**Issue by vivek-patel-NF** [jessjohn1539/Google-Maps-Lead-Scraper-using-Selenium#1]
![image](https://github.com/user-attachments/assets/42550829-2354-4fa9-a5ad-175504406c37)
![image](https://github.com/user-attachments/assets/4178103b-b898-4d1d-84b7-b3a2b81be2bf)

**Comment by jessjohn1539** [comment]
Thank you @vivek-patel-NF for addressing this issue, I've fixed it in the latest commit:
Here's what I did,

- Implemented a check for direct matches between the search query and the first 'h1' tag text.
- Modified the scraper to directly extract business data if there's a match, skipping unnecessary clicks.

If you liked this project, feel free to give it a star!!
